services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - excel_data:/app/src/excel_data/data
      - archives_data:/app/src/archives/data
      - images_data:/app/src/images/uploads
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=swiftpacklabel
      - POSTGRES_PASSWORD=swiftpacklabel123
      - POSTGRES_DB=swiftpacklabel

  celery-worker:
    build: .
    command: celery -A src.celery_app.celery worker --loglevel=info --concurrency=4 --queues=celery,supplies,orders,wildberries,notifications
    volumes:
      - excel_data:/app/src/excel_data/data
      - archives_data:/app/src/archives/data
      - images_data:/app/src/images/uploads
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=swiftpacklabel
      - POSTGRES_PASSWORD=swiftpacklabel123
      - POSTGRES_DB=swiftpacklabel
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A src.celery_app.celery beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - excel_data:/app/src/excel_data/data
      - archives_data:/app/src/archives/data
      - images_data:/app/src/images/uploads
      - celerybeat_data:/tmp
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=swiftpacklabel
      - POSTGRES_PASSWORD=swiftpacklabel123
      - POSTGRES_DB=swiftpacklabel
    restart: unless-stopped

  flower:
    build: .
    command: celery -A src.celery_app.celery flower --port=5555 --broker=redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: swiftpacklabel
      POSTGRES_USER: swiftpacklabel
      POSTGRES_PASSWORD: swiftpacklabel123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swiftpacklabel"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --databases 16
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  excel_data:
  archives_data:
  images_data:
  redis_data:
  celerybeat_data:
  postgres_data: